import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ dbdiagram, editor }) {
  

  
  return (
    <html lang="en">
      <body>
        <main className='w-full bg-black grid grid-cols-4 h-screen grid-rows-1'>
          {editor}
          {dbdiagram}
        </main>

      </body>
    </html>
  )
}
